name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests before deploy
        run: bun test

      - name: Deploy to Cloudflare Workers
        run: bunx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Post deployment notification
        if: success()
        run: |
          echo "🚀 Successfully deployed to Cloudflare Workers!"
          echo "🌐 Available at: https://aipictors-db.aipictors.workers.dev/"

      - name: Post failure notification
        if: failure()
        run: |
          echo "❌ Deployment failed. Please check the logs and try again."
